# Generated by Django 5.2.8 on 2025-11-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('restaurant_id', models.BigIntegerField(db_column='restaurantId', db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, db_column='imageUrl', max_length=500, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, db_column='imageUrl', max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('restaurant_id', models.BigIntegerField(db_column='restaurantId', db_index=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(db_column='menuId', on_delete=django.db.models.deletion.CASCADE, related_name='categories_menu', to='catalogue.menu')),
            ],
            options={
                'db_table': 'categories_menu',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('name', models.CharField(max_length=255)),
                ('restaurant_id', models.BigIntegerField(db_column='restaurantId', db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, db_column='imageUrl', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='catalogue.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'db_table': 'products_category',
                'unique_together': {('category', 'product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalogue.ProductCategory', to='catalogue.category'),
        ),
        migrations.CreateModel(
            name='ProductCategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalogue.categorymenu')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'db_table': 'products_category_menu',
                'unique_together': {('category', 'product')},
            },
        ),
    ]
