# Generated by Django 5.2.11 on 2026-02-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant_id',
            field=models.CharField(db_column='restaurantId', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_id',
            field=models.CharField(db_column='restaurantId', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant_id',
            field=models.CharField(db_column='restaurantId', db_index=True, max_length=50),
        ),
    ]
